server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zly1991/springcloudconfigs-zhou
          username: zly1991
          password: 19911211aili
          search-paths: /**
      label: master

#http://localhost:8089/dev/test/