server:
  port: 8084
spring:
  application:
    name: eureka-client
  redis:
    host: localhost
    port: 6379
    password:
  activemq:
    broker-url: tcp://localhost:61616
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka